version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    hostname: rabbitmq
    networks:
      - mynetwork
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: "exit 0"

  server-app:
    image: text-analyzer-server-app
    build: server
    restart: always
    networks:
      - mynetwork
    hostname: server-app
    ports:
      - 8089:8089
    depends_on:
      - rabbitmq
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: "exit 0"

  text-analyzer:
    image: text-analyzer
    build: text_analyzer
    restart: always
    networks:
      - mynetwork
    depends_on:
      - server-app
    stop_grace_period: 5m
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1G

  client:
    image: text-analyzer-client
    build:
      context: ./client
      args:
        - SERVER_URL=${SERVER_URL}
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server-app
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  mynetwork:
